# Generated by Django 4.0.6 on 2024-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ilustraciones')),
            ],
        ),
        migrations.CreateModel(
            name='Ilustracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('es_tatuaje', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('categorias', models.ManyToManyField(to='portfolio.categoria')),
                ('imagenes', models.ManyToManyField(blank=True, related_name='ilustraciones', to='portfolio.imagen')),
            ],
            options={
                'verbose_name': 'Ilustración',
                'verbose_name_plural': 'Ilustraciones',
            },
        ),
    ]
